### ISSUE TITLE
feat: go-to-definition for source files rather than from generated config schema result

### ISSUE THREAD

**Issue by ilyavolodin** [graphql/vscode-graphql#207]
## Actual Behavior

When using "Go to definition" in one of the .graphql files, it always opens auto-generated generated-schema.graphql file, instead of the source code.

## Expected Behavior

Correctly navigate to the source file.

## Steps to Reproduce the Problem Or Description

.graphqlrc.yml file:
```
overwrite: true
schema:
  - "./src/typeDefs/*.graphql"
generates:
  ./src/schema.generated.ts:
    plugins:
      - "typescript"
      - "typescript-resolvers"
    config:
      noSchemaStitching: true
      optionalInfoArgument: true
      contextType: ./context#Context
  ./types/generated.ts:
    plugins:
      - "typescript"
    config:
      noSchemaStitching: true
```

This is in apollo server project. All schema files are located in the same folder: `./src/typeDefs/*.graphql`. I have a number of .graphql files that have type definitions for the server. This is happening to all types, as far as I can tell.

## Specifications

  - GraphQL for VSCode Extension Version: v0.3.1
  - VSCode Version: 1.47.3
  - OS Name: OSX Mojave
  - OS Version: 10.14.6

## Logs Of TS Server || GraphQL Language Service

<details>
  <summary>Logs</summary>

  ```text
8/31/2020, 12:43:37 PM [4] (pid: 90841) graphql-language-service-usage-logs: {"type":"usage","messageType":"initialize"}

undefined
8/31/2020, 12:43:37 PM [4] (pid: 90841) graphql-language-service-usage-logs: {"type":"usage","messageType":"textDocument/didOpen","projectName":"default","fileName":"file:///Users/ivolodin/Code/orchestration/src/typeDefs/comments.graphql"}

undefined
[Error - 12:43:42 PM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Definition not found for GraphQL type CommentEdge
  Code: -32603 
8/31/2020, 12:43:43 PM [4] (pid: 90841) graphql-language-service-usage-logs: {"type":"usage","messageType":"textDocument/definition","projectName":"default","fileName":"file:///Users/ivolodin/Code/orchestration/src/typeDefs/comments.graphql"}

undefined
8/31/2020, 12:43:43 PM [4] (pid: 90841) graphql-language-service-usage-logs: {"type":"usage","messageType":"textDocument/didClose","projectName":"default","fileName":"file:///var/folders/lq/qs7z73kn4fb7b2csz2j323943khnrg/T/graphql-language-service/orchestration/projects/default/generated-schema.graphql"}

undefined
8/31/2020, 12:43:43 PM [4] (pid: 90841) graphql-language-service-usage-logs: {"type":"usage","messageType":"textDocument/didOpen","projectName":"default","fileName":"file:///var/folders/lq/qs7z73kn4fb7b2csz2j323943khnrg/T/graphql-language-service/orchestration/projects/default/generated-schema.graphql"}

undefined
8/31/2020, 12:43:45 PM [4] (pid: 90841) graphql-language-service-usage-logs: {"type":"usage","messageType":"textDocument/definition","projectName":"default","fileName":"file:///Users/ivolodin/Code/orchestration/src/typeDefs/comments.graphql"}

undefined
8/31/2020, 12:43:45 PM [4] (pid: 90841) graphql-language-service-usage-logs: {"type":"usage","messageType":"textDocument/didClose","projectName":"default","fileName":"file:///var/folders/lq/qs7z73kn4fb7b2csz2j323943khnrg/T/graphql-language-service/orchestration/projects/default/generated-schema.graphql"}

undefined
8/31/2020, 12:43:46 PM [4] (pid: 90841) graphql-language-service-usage-logs: {"type":"usage","messageType":"textDocument/didOpen","projectName":"default","fileName":"file:///var/folders/lq/qs7z73kn4fb7b2csz2j323943khnrg/T/graphql-language-service/orchestration/projects/default/generated-schema.graphql"}

undefined
8/31/2020, 12:43:46 PM [4] (pid: 90841) graphql-language-service-usage-logs: {"type":"usage","messageType":"textDocument/definition","projectName":"default","fileName":"file:///Users/ivolodin/Code/orchestration/src/typeDefs/comments.graphql"}

undefined
8/31/2020, 12:43:46 PM [4] (pid: 90841) graphql-language-service-usage-logs: {"type":"usage","messageType":"textDocument/didOpen","projectName":"default","fileName":"file:///var/folders/lq/qs7z73kn4fb7b2csz2j323943khnrg/T/graphql-language-service/orchestration/projects/default/generated-schema.graphql"}

undefined
  ```
</details>

**Comment by acao** [comment]
@ilyavolodin thanks for reporting - this is a known issue. we will expose the config option in the next patch release, which you'll be able to configure from vscode settings to default to source files (the setting is there, just doesn't work yet). by community demand, we went with a schema-first approach by default!

**Comment by acao** [comment]
ah! i almost forgot i made this [overridable at the `graphql-config` level](https://github.com/graphql/graphiql/blob/6114f2af3cc645677e6ebc8438dbec05d7ff1705/packages/graphql-language-service-server/src/MessageProcessor.ts#L842).

the namespace and config option don't make much sense so they will change for the next release, thus I won't add this to the readme yet, but the best workaround for this in 0.3.1 will be having this in your `graphql-config`:

```yml
extensions:
  vscode: 
    cacheSchemaFiles: true
    cacheConfigSchema: false
```

the reasons this namespace doesn't make sense are: 
- vim, sublime and other IDE users are using the same LSP server
- `cacheSchemaFiles` makes much less sense than `useSchemaFileDefinitions` or something else thats more clear

if anyone wants to make the vscode extension checkbox setting for this work in a PR, and in general make it stable enough to document, I've already got the settings loading LSP server side in `MessageProcessor` now, so you would just bring them into the `_cacheSchemaFilesForProject` method that I link to above!

**Comment by acao** [comment]
possibly because these options are mutually exclusive (using them together in theory is possible given the logic, but it seems the generated schema always overrides the source definitions. there is a use case here, where people use SDL source files that don't represent the generated schema. we had a setup like this at hilton)

- `definitionSource` of `file` or `config`, with `config` as default?
- even simpler: `useSchemaFileDefinitions` could just be false by default, and then if `true`, the source files would be used.

**Comment by acao** [comment]
> ah! i almost forgot i already made this [overridable at the `graphql-config` level](https://github.com/graphql/graphiql/blob/6114f2af3cc645677e6ebc8438dbec05d7ff1705/packages/graphql-language-service-server/src/MessageProcessor.ts#L842).
> 
> the namespace and config option don't make much sense so they will change for the next release, thus I won't add this to the readme yet, but the best workaround for this in 0.3.1 will be having this in your `graphql-config`:
> 
> ```yaml
> extensions:
>   vscode: 
>     cacheSchemaFiles: true
>     cacheConfigSchema: false
> ```
> 
> the reasons this namespace doesn't make sense are:
> 
>     * vim, sublime and other IDE users are using the same LSP server
> 
>     * `cacheSchemaFiles` makes much less sense than `useSchemaFileDefinitions` or something else thats more clear
> 
> 
> if anyone wants to make the vscode extension checkbox setting for this work in a PR, and in general make it stable enough to document, I've already got the settings loading LSP server side in `MessageProcessor` now, so you would just bring them into the `_cacheSchemaFilesForProject` method that I link to above!

@ilyavolodin did this fix your issue?

**Comment by acao** [comment]
We've released a version that allows you to set this from the vscode extension settings UI as well. Works great in my tests. Enjoy!

**Comment by zatloeri** [comment]
This problem still occurs for me.
I have these minimal settings:
```
schema: "./src/api/**/*.gql"
documents: null
extensions:
  vscode: 
    cacheSchemaFiles: true
    cacheConfigSchema: false
```

And I have two files in `./src/api/Users.gql ` and `./src/api/Messages.gql`

**Users.gql**
```
type User {
    id: ID!
    messages: [Message!]!
}
```

**Messages.gql**
```
type Message {
    id: ID!
    body: String!
    createdAt: String
}
```

My `.vscode/settings.json` are 
```
{
    "vscode-graphql.useSchemaFileDefinition": true,
}
```

And I am getting this message when I try to trigger the **go-to definition action on Message**:
```
[Error - 7:39:36 PM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Definition not found for GraphQL type Message
  Code: -32603 
```
They it directs me to the `generated-schema.graphql`
Also I am getting no autocomplete suggestions
Am I doing something wrong or is it problem with the extension?

**Comment by acao** [comment]
are you using insiders or `GraphQL.vscode-graphql@0.3.8`?

**Comment by acao** [comment]
I was able to get this working locally, but I'll spend some more time on tracing it down tomorrow. Apologies for the persistant issues!
If you can create an example repo, that would help me tremendously. All the info i need is there, just less steps with everything going on. Thank you!

**Comment by acao** [comment]
@zatloeri also, check the readme for updates, these options are now documented and have changed slightly. the vscode settings.json one should be enough for this to work, though
